class HomePageLocators:
    TRIP_TYPE_DROPDOWN = '[data-test^="SearchFormModesPicker-active-"]'
    TRIP_TYPE_ONEWAY = '[data-test="ModePopupOption-oneWay"]'
    FROM_INPUT = '[id="origin"]'
    TO_INPUT = '[id="destination"]'
    DATE_INPUT = '[data-test="SearchDateInput"]'
    FUTURE_DATE = '[data-test="CalendarDay"]'
    BOOKING_CHECKBOX = '[data-test="accommodationCheckbox"]'
    SEARCH_BUTTON = '[data-test="LandingSearchButton"]'
    ACCEPT_COOKIES = '[data-test="CookiesPopup-Accept"]'
    TRAVEL_CHIP_CLOSE = '[data-test="PlacePickerInputPlace-close"]'
    SUGGESTION_FILTER = '[data-test="PlacePickerRow-station"]'
    SET_DATES_BUTTON = '[data-test="SearchFormDoneButton"]'
    SEARCH_RESULTS = '[data-test="SearchResultsView"]'